### ISSUE TITLE
FPS count

### ISSUE THREAD

**Issue by JoseSoares96** [Aminullah6264/LiteFlowNet-for-Video#1]
HI there, 
I made a few changes from the original folder and yours, and got mine to compile how i wanted too.
My question is, **how many FPS can u get with this?**

**Comment by aminullah6264** [comment]
Hi, 
It is depending on your GPU power. I don't exactly remember the FPS for optical flow generation. However along with my action recognition algorithm it was taking 0.83 seconds to process 30 frames on TitanX GPU with 12 GB memory.

**Comment by JoseSoares96** [comment]
Thanks for the answer. Have a good one
